name: monitoring

services:
  prometheus:
    image: prom/prometheus:v3
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://monitor.qcc-mvp.grok-digital.com/prometheus/'
      - '--web.route-prefix=/'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - drone-net

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=https://monitor.qcc-mvp.grok-digital.com
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - drone-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro,rslave
    command: --path.rootfs=/host
    networks:
      - drone-net

  smartctl-exporter:
    image: prometheuscommunity/smartctl-exporter
    container_name: smartctl-exporter
    privileged: true
    restart: unless-stopped
    volumes:
      - /dev:/dev
    networks:
      - drone-net

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    container_name: prometheus-nginx-exporter
    restart: unless-stopped
    ports:
      - "9113:9113"
    command:
      - -nginx.scrape-uri=http://nginx/nginx_metrics
    networks:
      - drone-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "7070:8080"
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /run/containerd:/run/containerd:ro
    networks:
      - drone-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    # ports:
    #   - "9080:9080"
    restart: unless-stopped
    networks:
      - drone-net

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - drone-net

networks:
  drone-net:
    external: true

volumes:
  prometheus_data:
    name: prometheus_data
    external: true
  grafana_data:
    name: grafana_data
    external: true
  loki_data:
    name: loki_data
    external: true