{
 "title": "Host Metrics",
 "tags": [
  "final",
  "mvp-qcc-dfr"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "VM Resource Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Used"
    }
   ]
  },
  {
   "title": "Memory Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "MEM Used "
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_free_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"} / node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}))",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_free_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"} / node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\"}))",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Network  Errors ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_errs_total[5m]))\n+\nsum(rate(node_network_transmit_errs_total[5m]))",
     "legendFormat": "Network Errors "
    }
   ]
  },
  {
   "title": "Container Restarts (1h)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(container_start_time_seconds{name!=\"\"}[1h]))",
     "legendFormat": "Container Restart"
    }
   ]
  },
  {
   "title": "Uptime (Hours)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds - node_boot_time_seconds)/3600",
     "legendFormat": "Container Uptime"
    }
   ]
  },
  {
   "title": "System Load (5m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "System Load" }
   ]
  },
  {
   "title": "Disk Pressure (Latency)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_weighted_seconds_total[1m]))",
     "legendFormat": "Disk Pressure (Latency)"
    }
   ]
  },
  { "title": "VM Disk & IO Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "IO Wait %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[2m])) * 100",
     "legendFormat": "IO WAIT"
    }
   ]
  },
  {
   "title": "Disk Busy %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(rate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "Disk Busy "
    }
   ]
  },
  { "title": "VM Disk Deep Dive ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Disk Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "Disk Read "
    }
   ]
  },
  {
   "title": "Disk Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "Disk Write"
    }
   ]
  },
  { "title": "VM Network ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\".*\",name=~\".*\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\".*\",name=~\".*\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VM Health Score ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) * 100\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(container_restarts_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}